apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-lab-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - nginx.lab.local
      secretName: nginx-lab-tls
  rules:
    - host: nginx.lab.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-lab-svc
                port:
                  number: 80