apiVersion: v1
kind: Service
metadata:
  name: nginx-lab-metrics
  labels:
    app.k8s-monitor: nginx
spec:
  selector:
    app: nginx-lab
  ports:
    - name: metrics
      port: 9113
      targetPort: 9113