apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-labsec
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-labsec
  template:
    metadata:
      labels:
        app: nginx-labsec
    spec:
      containers:
      - name: nginx
        image: eberlin/nginx-lab:1.0.6
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80