apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-labsec-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
    - hosts: 
        - nginx.labsec.local
      secretName: nginx-labsec-tls
  rules:
  - host: nginx.labsec.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-labsec-svc
            port:
              number: 80